## Задачи для совместного разбора

In [ ]:
# from torchtyping import TensorType, patch_typeguard
# from typeguard import typechecked
import torch as th

# Scalar = TensorType[()]
# patch_typeguard()

1\. Обсудите подходы к решению задачи классификации на примере синтетического датасета.

In [ ]:
num_samples = 1000
num_features = 10
num_classes = 3

X = th.randn(num_samples, num_features)
y = th.randint(0, num_classes, (num_samples, ))

In [ ]:
import torch.nn as nn

class Classifier(nn.Module):
  def __init__(self, n_inputs: int, n_classes: int) -> None:
    super().__init__()
    self.fc1 = nn.Linear(n_inputs, n_classes)

  def forward(self, X: th.Tensor) -> th.Tensor:
    return self.fc1(X)

In [ ]:
model = Classifier(num_features, num_classes)
preds = model(X)
preds.shape

torch.Size([1000, 3])

In [ ]:
preds[:5]

tensor([[-0.8924,  1.3202, -0.6932],
        [ 0.6467, -1.1694,  0.6704],
        [ 0.7910, -0.4342, -1.0113],
        [ 0.2818, -0.4795, -0.3514],
        [ 0.4975,  0.5136, -1.6997]], grad_fn=<SliceBackward0>)

In [ ]:
preds.argmax(dim=1)[:5]

tensor([1, 2, 0, 0, 1])

In [ ]:
y[:5]

tensor([2, 0, 2, 0, 2])

In [ ]:
criterion = nn.CrossEntropyLoss()
loss = criterion(preds, y)

tensor(1.1765, grad_fn=<NllLossBackward0>)

In [ ]:
num_samples = 1000
num_features = 10
num_classes = 2

X = th.randn(num_samples, num_features)
y = th.randint(0, num_classes, (num_samples, ))

In [ ]:
import torch.nn as nn

class Classifier(nn.Module):
  def __init__(self, n_inputs: int, n_classes: int) -> None:
    super().__init__()
    self.fc1 = nn.Linear(n_inputs, n_classes)

  def forward(self, X: th.Tensor) -> th.Tensor:
    return self.fc1(X)

In [ ]:
model = Classifier(num_features, 1)
preds = model(X)

In [ ]:
preds.shape

torch.Size([1000, 1])

In [ ]:
preds.sigmoid()[:5]

tensor([[0.7246],
        [0.2931],
        [0.4752],
        [0.6542],
        [0.3030]], grad_fn=<SliceBackward0>)

In [ ]:
(preds.sigmoid() >= 0.5)[:5]

tensor([[ True],
        [False],
        [False],
        [ True],
        [False]])

In [ ]:
y[:5]

tensor([1, 0, 0, 1, 0])

In [ ]:
criterion = nn.BCEWithLogitsLoss()

criterion(preds.flatten(), y.float())

tensor(0.7429, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)

## Задачи для самостоятельного решения

<p class="task" id="1"></p>

1\. Используя реализацию полносвязного слоя из `torch.nn`, решите задачу классификации. Разделите датасет на обучающую и тестовую выборку в соотношении 80% на 20%. В качестве функции потерь используйте реализацию `CrossEntropyLoss` из `torch.nn`. Для настройки весов реализуйте мини-пакетный градиентный спуск с использованием `torch.optim.SGD`.

Используйте модель, состоящую из двух слоев:
1. Полносвязный слой с 10 нейронами;
2. Полносвязный слой с 2 нейронами.

Выведите график изменения значения функции потерь в процессе обучения. Выведите на экран значения Accuracy, Precision, Recall и F1 для обучающего и тестового множества.

Выведите на экран облако точек с цветом, соответствующим предсказаниям модели на всем датасете (и обучающей, и тестовой части).

- [ ] Проверено на семинаре


In [ ]:
from sklearn.datasets import make_circles
import torch as th
import torch.nn as nn
import torch.optim as optim

X, y = make_circles(n_samples=1000, noise=0.05, random_state=42)
X = th.FloatTensor(X)
y = th.LongTensor(y)

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

(torch.Size([800, 2]),
 torch.Size([200, 2]),
 torch.Size([800]),
 torch.Size([200]))

In [ ]:
model = nn.Sequantial(
    nn.Linear(in_features=2, out_features=10),
    nn.Linear(in_features=10, out_features=2)
)
criterion = nn.CrossEntropyLoss()
optimizer = optim()

<p class="task" id="2"></p>

2\. Повторите задачу 1, используя другую архитектуру нейронной сети.

1. Полносвязный слой с 10 нейронами;
2. Функция активации ReLU;
3. Полносвязный слой с 2 нейронами.

- [ ] Проверено на семинаре

<p class="task" id="3"></p>

3\. `CrossEntropyLoss` может быть использована для задачи классификации на любое количество классов. Для задачи бинарной классификации существуют специфические функции потерь. Решите задачу 2, используя `BCEWithLogitsLoss` в качестве функции потерь.

- [ ] Проверено на семинаре

<p class="task" id="4"></p>

4\. На практике часто задача классификации является несбалансированной. В файлах каталога `imb_task` содержится несбалансированный набор данных. Обучите модель без учета несбалансированности классов (аналогично предыдущим заданиям, можно использовать любую подходящую функцию потерь). Повысьте качество модели (в смысле F1) путем модификации функции потерь (указания специального аргумента, позволяющего учесть несбалансированность классов).

- [ ] Проверено на семинаре

<p class="task" id="5"></p>

5\. Повторите решение задачи 4, повысив качество модели за счет использования `WeightedRandomSampler` вместо модификации функции потерь.

- [ ] Проверено на семинаре